FROM elasticsearch:7.3.1
# COPY --chown=elasticsearch:elasticsearch elasticsearch.yml /usr/share/elasticsearch/config/

# To Build
# docker build --tag=elasticsearch-custom .
# docker run -ti -v /usr/share/elasticsearch/data elasticsearch # pass the volume.

# docker run -p 9200:9200 -p 9300:9300 \
# -e "discovery.type=single-node" \
# -e ES_JAVA_OPTS="-Xms256m -Xmx256m" \
# elasticsearch:7.3.1

# -v full_path_to/custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml \
# elasticsearch:7.3.1

